--- Specifications of Lua structures used in the docs ---
-- NAME   - DESCRIPTION
-- vec2f  - two elements array consisting of X and Y coords
-- vec2i  - the same as before, but limited to integers only
-- item   - a table containing three keys: (string) name, (int) count, (table) data
-- rect4f - eight elements array specifying a rectangle: minX, minY, maxX, maxY